### ISSUE TITLE
grunt not working in dev mode

### ISSUE THREAD

**Issue by basselkassem** [melmo/shwib#5]
When run:
grunt dev
## it didn't work and gave this message:

Warning: You need to have Ruby and Sass installed and in your PATH for
this task to work. More info:
https://github.com/gruntjs/grunt-contrib-sass Use --force to continue.
## Aborted due to warnings.

I think it needs sass plugins
any it worked after: 
npm install grunt-contrib-sass --save-dev

**Comment by melmo** [comment]
Added to package.json. Thanks.
